import type { NextPage } from "next";
import Head from "next/head";
import styles from '../../styles/Dashboard.module.css'
import React, { useState, useEffect, useContext } from "react";
import { useRouter } from "next/router"
import { UserContext } from "../../context/UserProvider";
import Router from "next/router";

const cups: NextPage = () => {
    const router = useRouter();
    const {
      query: { id },
    } = router;

    const user = useContext(UserContext);
  
    return (
      <div className={styles.container}>
        <Head>
          <title>Cups</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h2>Cups</h2>
        
      </div>
    )
  }
    
    export default cups