import type { NextPage } from "next";
import Head from "next/head";
import homestyles from '../styles/Home.module.css'
import React, { useState, useEffect, useContext } from "react";
import { useRouter } from "next/router"

const Dashboard: NextPage = () => {
    const router = useRouter();
    const {
      query: { id },
    } = router;
  
    return (
      <div className={homestyles.container}>
        <Head>
          <title>Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
      </div>
    )
  }
    
    export default Dashboard