import React, { useState, useContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Router from "next/router";
import createCupStyles from "../styles/createcup.module.css";
import { makeStyles } from "@material-ui/core/styles";
import Stack from "@mui/material/Stack";
import IconButton from "@mui/material/IconButton";
import Button from "@mui/material/Button";
import Grid from "@mui/material/Grid";
import TextField from "@mui/material/TextField";
import { UserContext } from "../context/UserProvider";

const useStyles = makeStyles((theme) => ({
  textField: {
    [`& fieldset`]: {
      borderRadius: 25,
    },
    "&": {
      marginTop: "9px",
    },
    "& .MuiInputBase-input": {
      borderRadius: 25,
      fontFamily: "Space Mono",
      fontSize: 20,
      color: "#ffffff",
      backgroundColor: "rgba(47, 56, 105, 0.6)",
      width: 500,
      padding: "15px 15px",
    },
  },
}));

const JoinCup: NextPage = () => {
  const user = useContext(UserContext);
  const classes = useStyles();

  return (
    <div className={createCupStyles.page}>
      <Head>
        <title>Join Cup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={createCupStyles.header}>
        <h1>Join a Cup</h1>
        <h6>View Open Cups or search for a specific Cup.</h6>
      </div>
      <div className={createCupStyles.container}></div>
    </div>
  );
};
export default JoinCup;
