import type { NextPage } from "next";
import cupstyles from "../styles/Cups.module.css";
import { useRouter } from "next/router";
import { db } from "../config/firebase.config";
import {
  collection,
  getDocs,
  QueryDocumentSnapshot,
  DocumentData,
} from "firebase/firestore";
import { useState, useEffect } from "react";
import Board from "../Components/Leaderboards";
import Head from "next/head";

const Leaderboard: NextPage = () => {
  const [leaderboard, setLeaderboard] = useState<
    QueryDocumentSnapshot<DocumentData>[]
  >([]);
  const [loading, setLoading] = useState<boolean>(true);
  const usersRef = collection(db, "users");

  useEffect(() => {
    const getLeaderboard = async () => {
      const data = await getDocs(usersRef);
      const result: QueryDocumentSnapshot<DocumentData>[] = [];
      data.forEach((c) => {
        result.push(c);
      });
      // setCups(data.docs.map((item)=>{
      //     return {...item.data(),id:item.id}
      // }));

      setLeaderboard(result);
      // setLoading(false);
    };
    getLeaderboard();
    setTimeout(() => {
      setLoading(false);
    }, 2000);
  }, []);

  const router = useRouter();
  const {
    query: { id },
  } = router;

  return (
    <div className={cupstyles.padding}>
      <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Leaderboards</h1>
      <h4>Global Leaderboards: Total Wins</h4>
      <Board cupid={""} />
    </div>
  );
};

export default Leaderboard;
