import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from "next/router"
import Logo from "./Icons/Logo.js";
import LaunchButton from "./Components/LaunchButton.js";
import Graph from "./Icons/Graph.js";
import Grid from '@mui/material/Grid';

const Login: NextPage = () => {
    const router = useRouter()
  const {
    query: { id },
  } = router
  
    return (
      <div className={styles.container}>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <div className={styles.navbar}>
          <div className={styles.containerLogo}>
            <div className={styles.logo}>
              <Logo />
            </div>
            <h2 className={styles.title}>Crypto Cup</h2>
          </div>
          <div className={styles.launch}>
            <h6 className={styles.about}>ABOUT</h6>
            <h6 className={styles.faq}>FAQ</h6>
            <div className={styles.launchButton}>
              <LaunchButton variant="contained">LAUNCH</LaunchButton>
            </div>
          </div>
        </div>

        <Grid container spacing={1}>
          <Grid item xs={6}>
            <h1 className={styles.title}>
              Log In or Sign up
            </h1>
            <div className="form-group">
                <label>Email</label>
                <input name="username" />
            </div>
            <div className="form-group">
                <label>Password</label>
                <input name="password" />
            </div>
            <p>Forgot Password?</p>
            <p>Remember Me</p>
            <button className="btn btn-primary">
                {<span className="spinner-border spinner-border-sm mr-1"></span>}
                Login
            </button>
          </Grid>

          <Grid item xs={6}>
            <div className={styles.graph}>
              <Graph />
            </div>
          </Grid>
        </Grid>
  
        
  
  
      </div>
    )
  }
  
  export default Login