import type { NextPage } from "next";
import Head from "next/head";
import cupstyles from '../styles/Cups.module.css'
import React, { useState, useEffect, useContext } from "react";
import {collection,getDocs,QueryDocumentSnapshot,DocumentData, Timestamp,addDoc} from "firebase/firestore";
import styles from '../styles/Profile.module.css'
import {db} from "../config/firebase.config"
import { useRouter } from "next/router"
import { UserContext } from "../context/UserProvider";
import Avatar from "@mui/material/Avatar";
import Grid from '@mui/material/Grid';
import moment from 'moment';

const Profile: NextPage = () => {
    const user = useContext(UserContext);
    const [cups,setCups]=useState<QueryDocumentSnapshot<DocumentData>[]>([]);
    const [loading,setLoading] = useState<boolean>(true);
    console.log(user);
    const cupsRef=collection(db,"cups");
    const getCups=async()=>{
        const data=await getDocs(cupsRef);
        const result: QueryDocumentSnapshot<DocumentData>[] = [];
        data.forEach((c)=>{
            result.push(c);
        }
        )
        // setCups(data.docs.map((item)=>{
        //     return {...item.data(),id:item.id}
        // }));
        
        setCups(result);
        // setLoading(false);
    };

    useEffect(()=>{
        getCups();
        setTimeout( () => {
            setLoading(false);
          },2000)
    },[]);
    const router = useRouter();
    const {
      query: { id },
    } = router;
    
  
    return (
      <div className={styles.container}>
        <Head>
          <title>Profile</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <div>
          <h1 className={styles.title}>
            Profile
          </h1>
          <h1 className={styles.info}>
            <Avatar
              sx={{ width: 100, height: 100 }}
              src={user.data.imageURL}
              alt={user.uid}
              />
          </h1>
          <h2 className={styles.info}>
            {user.data.firstName + " " + user.data.lastName}
          </h2>
          <h6 className={styles.subtitle}>
            {user.uid}
          </h6>
          
          <h5 className={styles.title}>
            Email
          </h5>
          <h6 className={styles.subtitle}>
            {user.email}
          </h6>

          <h5 className={styles.info}>
            Birthday
          </h5>
          <h6 className={styles.subtitle}>
            {!user.data.birthday? <div></div>:moment(user.data.birthday.toDate()).format("M/D/YYYY")}
          </h6>

          <h5 className={styles.info}>
            News Preferences
          </h5>
          <h6 className={styles.subtitle}>
            {!user.data.newsPreferences ? <div></div>: (user.data.newsPreferences.map((tag) => (
              <h6 className={styles.subtitle}>
                * {tag.toUpperCase()}
              </h6>
            )
            ))}
          </h6>

          <h2 className={styles.info}>
            Cup History
          </h2>
          <h6 className={styles.info}>
          {loading ? (<div>loading</div>) :
            <Grid container >
                {cups.map((c)=>
                    <Grid item xs={4}>
                        <h5>{c.get("name")}</h5>
                        <div className={cupstyles.cuptype}>{c.get("cupType")}</div>
                        <p>{moment(c.get("startDate")).format("M/D/YYYY")}-{moment(c.get("endDate")).format("M/D/YYYY")}</p>
                    </Grid>
                    )}
            </Grid>  
            }
            </h6>
            </div>
        </main>
      </div>
      
    )
  }
    
    export default Profile